# generated by agent_generator.rb, manual changes will be lost

class pacemaker::stonith::fence_kdump (
	$nodename = undef,
	$ipport = undef,
	$family = undef,
	$timeout = undef,
	$verbose = undef,
	$usage = undef,

	$interval = "60s",
	$ensure = present,
	$pcmk_host_value = undef,

) {
  $real_address = "$(corosync-cfgtool -a $(crm_node -n))"

  if($ensure == absent) {
    exec {
      "Removing stonith::fence_kdump":
      command => "/usr/sbin/pcs stonith delete stonith-fence_kdump-${real_address}",
      onlyif => "/usr/sbin/pcs stonith show stonith-fence_kdump-${real_address} > /dev/null 2>&1",
      require => Class["pacemaker::corosync"],
    }
  } else {
  	$nodename_chunk = $nodename ? {
		undef => "",
		default => "nodename=\"${nodename}\"",
	}
	$ipport_chunk = $ipport ? {
		undef => "",
		default => "ipport=\"${ipport}\"",
	}
	$family_chunk = $family ? {
		undef => "",
		default => "family=\"${family}\"",
	}
	$timeout_chunk = $timeout ? {
		undef => "",
		default => "timeout=\"${timeout}\"",
	}
	$verbose_chunk = $verbose ? {
		undef => "",
		default => "verbose=\"${verbose}\"",
	}
	$usage_chunk = $usage ? {
		undef => "",
		default => "usage=\"${usage}\"",
	}

    $pcmk_host_value_chunk = $pcmk_host_list ? {
      '' => '$(/usr/sbin/crm_node -n)',
      default => "${pcmk_host_list}",
    }

    package {
      "fence-agents-kdump": ensure => installed,
    } -> exec {
      "Creating stonith::fence_kdump":
      command => "/usr/sbin/pcs stonith create stonith-fence_kdump-${real_address} fence_kdump pcmk_host_list=\"${pcmk_host_value_chunk}\" ${nodename_chunk} ${ipport_chunk} ${family_chunk} ${timeout_chunk} ${verbose_chunk} ${usage_chunk}  op monitor interval=${interval}",
      unless => "/usr/sbin/pcs stonith show stonith-fence_kdump-${real_address} > /dev/null 2>&1",
      require => Class["pacemaker::corosync"],
    } -> exec {
      "Adding non-local constraint stonith::fence_kdump ${real_address}":
      command => "/usr/sbin/pcs constraint location stonith-fence_kdump-${real_address} avoids ${pcmk_host_value_chunk}"
    }
  }
}
