name 'puppet-galera'
version '0.0.2'
source 'https://github.com/rohara/puppet-galera'
author 'Ryan O\'Hara'
license 'Apache License 2.0'
summary 'Install/configure MariaDB with Galera'
description 'Install/configure MariaDB with Galera'
project_page 'https://github.com/rohara/puppet-galera'

dependency 'puppetlabs/mysql', '>= 0.5.0'
dependency 'puppetlabs/xinetd', '>= 1.2.0'
