name    'ghoneycutt-nfs'
version '1.7.0'
source 'git://github.com/ghoneycutt/puppet-module-nfs.git'
author 'ghoneycutt'
license 'Apache License, Version 2.0'
summary 'Manage NFS'
description 'Manage NFS for client and server, including idmap'
project_page 'https://github.com/ghoneycutt/puppet-module-nfs'

dependency 'ghoneycutt/common',  '>= 1.0.0'
dependency 'ghoneycutt/rpcbind', '>= 1.0.0'
dependency 'ghoneycutt/types',   '>= 1.1.0'
dependency 'puppetlabs/stdlib',  '>= 3.2.0'
