fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git" 
    concat:
      repo:   "https://github.com/puppetlabs/puppetlabs-concat.git"
      branch: "1.2.x"
    staging: "https://github.com/nanliu/puppet-staging.git"
  symlinks:
    tomcat: "#{source_dir}"
