HOSTS:
  centos-66-x64:
    roles:
      - master
    platform: el-6-x86_64
    box : puppetlabs/centos-6.6-64-nocm
    box_url : https://atlas.hashicorp.com/puppetlabs/boxes/centos-6.6-64-nocm
    hypervisor : vagrant
CONFIG:
  type: git
