name          'pauloconnor-uchiwa'
version       '0.1.0'
source        'github.com/pauloconnor/pauloconnor-uchiwa'
author        'pauloconnor'
license       'Apache 2.0'
summary       'Puppet module for installing Uchiwa'
description   'Puppet module for installing Uchiwa'
project_page  'https://github.com/pauloconnor/pauloconnor-uchiwa'

dependency 'puppetlabs/apt'
dependency 'puppetlabs/concat'
dependency 'puppetlabs/stdlib'
