fixtures:
  repositories:
    'inifile': 'git://github.com/puppetlabs/puppetlabs-inifile'
    'concat':
      'repo': 'git://github.com/puppetlabs/puppetlabs-concat.git'
      'ref': '1.2.1'
    'keystone': 'git://github.com/openstack/puppet-keystone.git'
    'mysql': 'git://github.com/puppetlabs/puppetlabs-mysql.git'
    'nova': 'git://github.com/openstack/puppet-nova.git'
    'openstacklib': 'git://github.com/openstack/puppet-openstacklib.git'
    'postgresql': 'git://github.com/puppetlabs/puppet-postgresql.git'
    'stdlib': 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
  symlinks:
    "heat": "#{source_dir}"
