fixtures:
  repositories:
    "inifile": "git://github.com/puppetlabs/puppetlabs-inifile"
    'concat': 'git://github.com/puppetlabs/puppetlabs-concat.git'
    "keystone":
      repo: "git://github.com/stackforge/puppet-keystone.git"
      ref: "origin/stable/juno"
    "mysql":
      repo: 'git://github.com/puppetlabs/puppetlabs-mysql.git'
      ref: 'origin/2.2.x'
    "nova":
      repo: "git://github.com/stackforge/puppet-nova.git"
      ref: "origin/stable/juno"
    'openstacklib': 'git://github.com/stackforge/puppet-openstacklib.git'
    'postgresql': 'git://github.com/puppetlabs/puppet-postgresql.git'
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
  symlinks:
    "heat": "#{source_dir}"
