AllCops:
  Exclude:
    - vendor/**/*
    - pkg/**/*
    - spec/fixtures/**/*

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 400

# dealbreaker:
Style/TrailingComma:
  Enabled: false

# we still support ruby 1.8
Style/HashSyntax:
  Enabled: false
