---
language: ruby
bundler_args: --without development
before_install:
  - rm Gemfile.lock || true
  # Fixes a rubygems bug that causes failures on Travis CI
  # See https://github.com/bundler/bundler/issues/2784
  - gem update --system 2.2.1
  - gem --version
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
script: "bundle exec rake test"
env:
  - PUPPET_VERSION="~> 3.0.1"
  - PUPPET_VERSION="~> 3.1.0"
  - PUPPET_VERSION="~> 3.2.0"
  - PUPPET_VERSION="~> 3.3.0"
  - PUPPET_VERSION="~> 3.4.0"
matrix:
  exclude:
  - rvm: 2.0.0
    env: PUPPET_VERSION="~> 3.0.1"
  - rvm: 2.0.0
    env: PUPPET_VERSION="~> 3.1.0"
