# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # CentOS 6.5
  #config.vm.box = 'centos6.5puppet'
  #config.vm.box_url = 'http://puppet-vagrant-boxes.puppetlabs.com/centos-65-x64-virtualbox-puppet.box'

  # Ubuntu 13.10
  config.vm.box = 'ubuntu12.04.2puppet'
  config.vm.box_url = 'http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210.box'

  config.vm.hostname = 'kibana3.thejandroman.local'

  # Configure RAM and CPU(s)
  config.vm.provider :virtualbox do |vb|
    vb.customize ['modifyvm', :id, '--memory', '512']
    vb.customize ['modifyvm', :id, '--cpus', 1]
    vb.customize ['setextradata', :id, 'VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root', '1']
  end

  config.vm.provision :shell, :path => 'default.sh'

  config.vm.provision :puppet do |puppet|
    puppet.module_path = '../..'
    #puppet.options = '--verbose --debug'
  end
end
