fixtures:
  repositories:
    'concat':
      'repo': 'git://github.com/puppetlabs/puppetlabs-concat.git'
      'ref': '1.2.1'
    'stdlib': 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
    'inifile': 'git://github.com/puppetlabs/puppetlabs-inifile'
    'keystone': 'git://github.com/openstack/puppet-keystone.git'
    'mysql': 'git://github.com/puppetlabs/puppetlabs-mysql.git'
    'nova': 'git://github.com/openstack/puppet-nova.git'
    'openstacklib': 'git://github.com/openstack/puppet-openstacklib.git'
    'postgresql': 'git://github.com/puppetlabs/puppet-postgresql.git'
    'vswitch': 'git://github.com/openstack/puppet-vswitch'
    'sysctl': 'git://github.com/duritong/puppet-sysctl.git'
  symlinks:
    "neutron": "#{source_dir}"
