fixtures:
  repositories:
    'firewall': 'git://github.com/puppetlabs/puppetlabs-firewall.git'
    'stdlib': 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
  symlinks:
    "tripleo": "#{source_dir}"
