fixtures:
  repositories:
    'firewall': 'git://github.com/puppetlabs/puppetlabs-firewall.git'
    'stdlib': 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
    'midonet':
      repo: 'git://github.com/midonet/puppet-midonet.git'
      ref: 'v2015.06.7'
    'tomcat':
      repo: 'git://github.com/puppetlabs/puppetlabs-tomcat.git'
      ref: '1.3.2'
    'inifile':
      repo: 'git://github.com/puppetlabs/puppetlabs-inifile.git'
      ref: '1.4.2'
    'cassandra':
      repo: 'git://github.com/locp/cassandra.git'
      ref: '1.9.2'
    'zookeeper':
      repo: 'git://github.com/deric/puppet-zookeeper.git'
      ref: 'v0.3.9'
    'datacat':
      repo: 'git://github.com/richardc/puppet-datacat'
      ref: '0.6.2'
    'java':
      repo: 'git://github.com/puppetlabs/puppetlabs-java'
      ref: '1.4.2'
  symlinks:
    "tripleo": "#{source_dir}"
