language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - ruby-head
script: "rake all"
branches:
  only:
    - rspec_infrastructure
env:
  - PUPPET_GEM_VERSION="~> 2.7"
  - PUPPET_GEM_VERSION="~> 3.3"
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 2.7"
notifications:
  email: false
  
