fixtures:
  repositories:
    'corosync': 'https://github.com/puppetlabs/puppetlabs-corosync'
    'apt'    : 'git://github.com/puppetlabs/puppetlabs-apt'
    'stdlib' : 'git://github.com/puppetlabs/puppetlabs-stdlib'
  symlinks:
    'openstack_extras': "#{source_dir}"
