HOSTS:
  first:
    roles:
      - master
      - mon
    platform: ubuntu-1204-amd64
    box: puppetlabs/ubuntu-12.04-64-nocm
    box_url: https://atlas.hashicorp.com/puppetlabs/boxes/ubuntu-12.04-64-nocm
    hypervisor: vagrant
    ip: 10.11.12.2
  second:
    roles:
      - osd
      - client
    platform: ubuntu-1204-amd64
    box: puppetlabs/ubuntu-12.04-64-nocm
    box_url: https://atlas.hashicorp.com/puppetlabs/boxes/ubuntu-12.04-64-nocm
    hypervisor: vagrant
    ip: 10.11.12.3
CONFIG:
  type: foss
