fixtures:
  forge_modules:
    apt:
      repo: "puppetlabs-apt"
      ref: "1.8.0"
    stdlib: "puppetlabs-stdlib"
    inifile: "puppetlabs-inifile"
    zookeeper: "deric-zookeeper"
    cassandra: "midonet-cassandra"
    datacat: "richardc-datacat"
    java: "puppetlabs-java"
    module_data: "ripienaar-module_data"
