name    'ghoneycutt-common'
version '1.2.0'
source 'git://github.com/ghoneycutt/puppet-module-common.git'
author 'ghoneycutt'
license 'Apache License, Version 2.0'
summary 'common module to be applied to all nodes'
description 'Provide ability to include modules that are common to all nodes.'
project_page 'https://github.com/ghoneycutt/puppet-module-common'

dependency 'puppetlabs/stdlib', '>= 3.2.0'
