fixtures:
  repositories:
    stdlib: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
    inifile: 'git://github.com/puppetlabs/puppetlabs-inifile'
    openstacklib: 'git://github.com/stackforge/puppet-openstacklib.git'
    glance: 'git://github.com/openstack/puppet-glance.git'
    vcsrepo: 'git://github.com/puppetlabs/puppetlabs-vcsrepo'
  symlinks:
    tempest: "#{source_dir}"
