name 'camptocamp-kmod'
version '0.0.1'
license 'Apache License, Version 2.0'
project_page 'git://github.com/camptocamp/puppet-kmod.git'
description 'Manage Linux kernel modules with Puppet'
summary 'Manage Linux kernel modules with Puppet'
