fixtures:
  repositories:
    'stdlib':
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.5.1'
    'file_concat':
      repo: 'git://github.com/electrical/puppet-lib-file_concat.git'
      branch: '1.0.0'
  symlinks:
    'concat': '#{source_dir}'
